# =============================================================================
# N8N AI STARTER KIT - PROMETHEUS CONFIGURATION
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files: []

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # N8N metrics (if available)
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Web Interface service
  - job_name: 'web-interface'
    static_configs:
      - targets: ['web-interface:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Document Processor service
  - job_name: 'document-processor'
    static_configs:
      - targets: ['document-processor:8001']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # ETL Processor service
  - job_name: 'etl-processor'
    static_configs:
      - targets: ['etl-processor:8002']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # LightRAG service
  - job_name: 'lightrag'
    static_configs:
      - targets: ['lightrag:8003']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # GPU Monitor service
  - job_name: 'gpu-monitor'
    static_configs:
      - targets: ['gpu-monitor:8014']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL metrics (using postgres_exporter if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 60s
    scrape_timeout: 15s

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: /metrics
    scrape_interval: 60s
    scrape_timeout: 15s

  # Docker container metrics (if cAdvisor is available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s